#!/usr/bin/env php
<?php

require_once 'SerializedToXML.php';
require_once 'SimpleXMLElementExtended.php';

if (!isset($argv[1])) {
    throw new Exception("Missing required argument <filename>");
}

// Right now this expects an example serialized array in a file
$file = $argv[1];
$data = file_get_contents($file);

$transformer = new SerializedToXML();
$xml = $transformer->unserialize($data);

print $xml;
