#!/usr/bin/env php
<?php
/**
 * A tool for splitting WXR (XML) documents into multiple files, each containing 1 post.
 *
 * @package Internet.org
 */

if ( ! isset( $argv[1] ) ) {
	throw new Exception( 'Missing required argument <input-file>' );
}
$filein = $argv[1];

if ( ! is_file( $filein ) ) {
	throw new Exception( 'Invalid input file specified' );
}

// defaulting to "serialized" as that's what are doing with content
$output_dir = 'split-files';
if ( isset( $argv[2] ) ) {
	$output_dir = $argv[2];
}

// create the directory if it doesn't exist
if ( ! is_dir( $output_dir ) ) {
	mkdir( $output_dir );
}



$dom = new DOMDocument;

$success = $dom->loadXML( file_get_contents( $filein ) );

$xml = simplexml_import_dom( $dom );

$namespaces = $xml->getDocNamespaces();

foreach ( $xml->channel->item as $item ) {

	$dc = $item->children( 'http://purl.org/dc/elements/1.1/' );

	$content = $item->children( 'http://purl.org/rss/1.0/modules/content/' );

	$wp = $item->children( $namespaces['wp'] );

	$string_out = '<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0"
	xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:wp="http://wordpress.org/export/1.2/"
>

<channel>
	<title>vip.local</title>
	<link>http://internetorgvip.nerderylabs.com</link>
	<description>Just another Vip.local site</description>
	<pubDate>Thu, 24 Sep 2015 22:21:36 +0000</pubDate>
	<language>en-US</language>
	<wp:wxr_version>1.2</wp:wxr_version>
	<wp:base_site_url>http://internetorgvip.nerderylabs.com/</wp:base_site_url>
	<wp:base_blog_url>http://internetorgvip.nerderylabs.com</wp:base_blog_url>

	<wp:author><wp:author_id>1</wp:author_id><wp:author_login><![CDATA[wordpress]]></wp:author_login><wp:author_email><![CDATA[admin@example.com]]></wp:author_email><wp:author_display_name><![CDATA[wordpress]]></wp:author_display_name><wp:author_first_name><![CDATA[]]></wp:author_first_name><wp:author_last_name><![CDATA[]]></wp:author_last_name></wp:author>

	<generator>http://wordpress.org/?v=4.4-alpha-34525</generator>
	';

	$string_out .= $item->asXML();

	$string_out .= '
</channel>
</rss>
';

	$post_id = (int) $wp->post_id;

	$fileout = $output_dir . DIRECTORY_SEPARATOR . $post_id . '.xml';

	$fh = fopen( $fileout, 'w' ) or die ( 'cant open file ' . $fileout );

	fwrite( $fh, $string_out );

	fclose( $fh );
}
